spring:
  application:
    name: eureka-server-peer2
server:
  port: 8892
eureka:
  instance:
    hostname: peer2
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  client:
    service-url:
      defaultZone: http://peer1:8891/eureka